---
name: Lint Code Base
on: [push, pull_request]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade ruff
          python -m pip install --upgrade black
          python -m pip install --upgrade mypy
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff check --diff --format=github .
      - name: Run Black
        uses: psf/black@stable
      - name: Run mypy
        run: mypy . --no-strict-optional --ignore-missing-imports
